module.exports = {
    siteMetadata: {
        title: `Hoe Zit Het?`,
        description: `Verlichte uitleg wiskunde en fysica`,
        author: `@hoezithet`,
        siteURL: `https://hoezithet.nu`,
    },
    plugins: [
        `gatsby-plugin-typescript`,
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/images`,
            },
        },
        `gatsby-plugin-sass`,
        `gatsby-transformer-sharp`,
        `gatsby-plugin-sharp`,
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `Hoe Zit Het?`,
                short_name: `hoezithet`,
                start_url: `/`,
                background_color: `#F4F4F4`,
                theme_color: `#FFB700`,
                display: `minimal-ui`,
                icon: `src/images/favicon.png`, // This path is relative to the root of the site.
            },
        },
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `markdown-pages`,
                path: `${__dirname}/src/content`,
            },
        },
        {
            resolve: `gatsby-transformer-remark`,
            options: {
                plugins: [
                    `gatsby-remark-autolink-headers`,
                    {
                        resolve: `gatsby-remark-images`,
                        options: {
                            // It's important to specify the maxWidth (in pixels) of
                            // the content container as this plugin uses this as the
                            // base for generating different widths of each image.
                            maxWidth: 590,
                            showCaptions: ["title"],
                            markdownCaptions: true,
                        },
                    },
                ],
            },
        },
        {
            resolve: `gatsby-transformer-remark`,
            options: {
                plugins: [
                    {
                        resolve: `gatsby-remark-katex`,
                        options: {
                            // Add any KaTeX options from https://github.com/KaTeX/KaTeX/blob/master/docs/options.md here
                            strict: `ignore`,
                            macros: {
                                "\\deg": "^{\\circ}",
                                "\\norm": ["\\lVert#1\\rVert", 1],
                                "\\breq": "\\stackrel{\\text{BR}}{=}",
                                "\\darkred": "\\color{#e7040f}",
                                "\\red": "\\color{#ff4136}",
                                "\\lightred": "\\color{#ff725c}",
                                "\\orange": "\\color{#ff6300}",
                                "\\gold": "\\color{#ffb700}",
                                "\\yellow": "\\color{#ffde37}",
                                "\\lightyellow": "\\color{#fbf1a9}",
                                "\\purple": "\\color{#5e2ca5}",
                                "\\lightpurple": "\\color{#a463f2}",
                                "\\darkpink": "\\color{#d5008f}",
                                "\\hotpink": "\\color{#ff41b4}",
                                "\\pink": "\\color{#ff80cc}",
                                "\\lightpink": "\\color{#ffa3d7}",
                                "\\darkgreen": "\\color{#137752}",
                                "\\green": "\\color{#19a974}",
                                "\\lightgreen": "\\color{#9eebcf}",
                                "\\navy": "\\color{#001b44}",
                                "\\darkblue": "\\color{#00449e}",
                                "\\blue": "\\color{#357edd}",
                                "\\lightblue": "\\color{#96ccff}",
                                "\\lightestblue": "\\color{#cdecff}",
                                "\\washedblue": "\\color{#f6fffe}",
                                "\\washedgreen": "\\color{#e8fdf5}",
                                "\\washedyellow": "\\color{#fffceb}",
                                "\\washedred": "\\color{#ffdfdf}",
                                "\\grey": "\\color{#d3d3d3}",
                                "\\gray": "\\color{#d3d3d3}",

                                "\\dblue": "\\color{#00449e}",
                                "\\black": "\\color{#000000}",
                                "\\pos": "\\color{#19a974}",
                                "\\neg": "\\color{#e7040f}",
                                "\\neut": "\\color{#357edd}",
                                "\\atten": "\\color{#ff6300}",
                                "\\link": "\\color{#357edd}",

                                "\\clra": "\\color{#ff6300}",
                                "\\clrb": "\\color{#00449e}",
                                "\\clrc": "\\color{#d5008f}",
                                "\\clrd": "\\color{#e7040f}",
                                "\\clre": "\\color{#19a974}",

                                "\\mute": "\\color{#d3d3d3}",

                                "\\si": "\\text",

                                "\\udotdarkred": "\\bbox[1pt,border-bottom: 2px dotted #e7040f]",
                                "\\udotred": "\\bbox[1pt,border-bottom: 2px dotted #ff4136]",
                                "\\udotlightred": "\\bbox[1pt,border-bottom: 2px dotted #ff725c]",
                                "\\udotorange": "\\bbox[1pt,border-bottom: 2px dotted #ff6300]",
                                "\\udotgold": "\\bbox[1pt,border-bottom: 2px dotted #ffb700]",
                                "\\udotyellow": "\\bbox[1pt,border-bottom: 2px dotted #ffde37]",
                                "\\udotlightyellow": "\\bbox[1pt,border-bottom: 2px dotted #fbf1a9]",
                                "\\udotpurple": "\\bbox[1pt,border-bottom: 2px dotted #5e2ca5]",
                                "\\udotlightpurple": "\\bbox[1pt,border-bottom: 2px dotted #a463f2]",
                                "\\udotdarkpink": "\\bbox[1pt,border-bottom: 2px dotted #d5008f]",
                                "\\udothotpink": "\\bbox[1pt,border-bottom: 2px dotted #ff41b4]",
                                "\\udotpink": "\\bbox[1pt,border-bottom: 2px dotted #ff80cc]",
                                "\\udotlightpink": "\\bbox[1pt,border-bottom: 2px dotted #ffa3d7]",
                                "\\udotdarkgreen": "\\bbox[1pt,border-bottom: 2px dotted #137752]",
                                "\\udotgreen": "\\bbox[1pt,border-bottom: 2px dotted #19a974]",
                                "\\udotlightgreen": "\\bbox[1pt,border-bottom: 2px dotted #9eebcf]",
                                "\\udotnavy": "\\bbox[1pt,border-bottom: 2px dotted #001b44]",
                                "\\udotdarkblue": "\\bbox[1pt,border-bottom: 2px dotted #00449e]",
                                "\\udotblue": "\\bbox[1pt,border-bottom: 2px dotted #357edd]",
                                "\\udotlightblue": "\\bbox[1pt,border-bottom: 2px dotted #96ccff]",
                                "\\udotlightestblue": "\\bbox[1pt,border-bottom: 2px dotted #cdecff]",
                                "\\udotwashedblue": "\\bbox[1pt,border-bottom: 2px dotted #f6fffe]",
                                "\\udotwashedgreen": "\\bbox[1pt,border-bottom: 2px dotted #e8fdf5]",
                                "\\udotwashedyellow": "\\bbox[1pt,border-bottom: 2px dotted #fffceb]",
                                "\\udotwashedred": "\\bbox[1pt,border-bottom: 2px dotted #ffdfdf]",
                                "\\udotgrey": "\\bbox[1pt,border-bottom: 2px dotted #d3d3d3]",
                                "\\udotgray": "\\bbox[1pt,border-bottom: 2px dotted #d3d3d3]",
                                "\\udot": "\\bbox[1pt,border-bottom: 2px dotted #d3d3d3]",

                                "\\udashdarkred": "\\bbox[1pt,border-bottom: 2px dashed #e7040f]",
                                "\\udashred": "\\bbox[1pt,border-bottom: 2px dashed #ff4136]",
                                "\\udashlightred": "\\bbox[1pt,border-bottom: 2px dashed #ff725c]",
                                "\\udashorange": "\\bbox[1pt,border-bottom: 2px dashed #ff6300]",
                                "\\udashgold": "\\bbox[1pt,border-bottom: 2px dashed #ffb700]",
                                "\\udashyellow": "\\bbox[1pt,border-bottom: 2px dashed #ffde37]",
                                "\\udashlightyellow": "\\bbox[1pt,border-bottom: 2px dashed #fbf1a9]",
                                "\\udashpurple": "\\bbox[1pt,border-bottom: 2px dashed #5e2ca5]",
                                "\\udashlightpurple": "\\bbox[1pt,border-bottom: 2px dashed #a463f2]",
                                "\\udashdarkpink": "\\bbox[1pt,border-bottom: 2px dashed #d5008f]",
                                "\\udashhotpink": "\\bbox[1pt,border-bottom: 2px dashed #ff41b4]",
                                "\\udashpink": "\\bbox[1pt,border-bottom: 2px dashed #ff80cc]",
                                "\\udashlightpink": "\\bbox[1pt,border-bottom: 2px dashed #ffa3d7]",
                                "\\udashdarkgreen": "\\bbox[1pt,border-bottom: 2px dashed #137752]",
                                "\\udashgreen": "\\bbox[1pt,border-bottom: 2px dashed #19a974]",
                                "\\udashlightgreen": "\\bbox[1pt,border-bottom: 2px dashed #9eebcf]",
                                "\\udashnavy": "\\bbox[1pt,border-bottom: 2px dashed #001b44]",
                                "\\udashdarkblue": "\\bbox[1pt,border-bottom: 2px dashed #00449e]",
                                "\\udashblue": "\\bbox[1pt,border-bottom: 2px dashed #357edd]",
                                "\\udashlightblue": "\\bbox[1pt,border-bottom: 2px dashed #96ccff]",
                                "\\udashlightestblue": "\\bbox[1pt,border-bottom: 2px dashed #cdecff]",
                                "\\udashwashedblue": "\\bbox[1pt,border-bottom: 2px dashed #f6fffe]",
                                "\\udashwashedgreen": "\\bbox[1pt,border-bottom: 2px dashed #e8fdf5]",
                                "\\udashwashedyellow": "\\bbox[1pt,border-bottom: 2px dashed #fffceb]",
                                "\\udashwashedred": "\\bbox[1pt,border-bottom: 2px dashed #ffdfdf]",
                                "\\udashgrey": "\\bbox[1pt,border-bottom: 2px dashed #d3d3d3]",
                                "\\udashgray": "\\bbox[1pt,border-bottom: 2px dashed #d3d3d3]",
                                "\\udash": "\\bbox[1pt,border-bottom: 2px dashed #d3d3d3]",

                                "\\usoliddarkred": "\\bbox[1pt,border-bottom: 2px solid #e7040f]",
                                "\\usolidred": "\\bbox[1pt,border-bottom: 2px solid #ff4136]",
                                "\\usolidlightred": "\\bbox[1pt,border-bottom: 2px solid #ff725c]",
                                "\\usolidorange": "\\bbox[1pt,border-bottom: 2px solid #ff6300]",
                                "\\usolidgold": "\\bbox[1pt,border-bottom: 2px solid #ffb700]",
                                "\\usolidyellow": "\\bbox[1pt,border-bottom: 2px solid #ffde37]",
                                "\\vusolidlightyellow": "\\bbox[1pt,border-bottom: 2px solid #fbf1a9]",
                                "\\usolidpurple": "\\bbox[1pt,border-bottom: 2px solid #5e2ca5]",
                                "\\usolidlightpurple": "\\bbox[1pt,border-bottom: 2px solid #a463f2]",
                                "\\usoliddarkpink": "\\bbox[1pt,border-bottom: 2px solid #d5008f]",
                                "\\usolidhotpink": "\\bbox[1pt,border-bottom: 2px solid #ff41b4]",
                                "\\usolidpink": "\\bbox[1pt,border-bottom: 2px solid #ff80cc]",
                                "\\usolidlightpink": "\\bbox[1pt,border-bottom: 2px solid #ffa3d7]",
                                "\\usoliddarkgreen": "\\bbox[1pt,border-bottom: 2px solid #137752]",
                                "\\usolidgreen": "\\bbox[1pt,border-bottom: 2px solid #19a974]",
                                "\\usolidlightgreen": "\\bbox[1pt,border-bottom: 2px solid #9eebcf]",
                                "\\usolidnavy": "\\bbox[1pt,border-bottom: 2px solid #001b44]",
                                "\\usoliddarkblue": "\\bbox[1pt,border-bottom: 2px solid #00449e]",
                                "\\usolidblue": "\\bbox[1pt,border-bottom: 2px solid #357edd]",
                                "\\usolidlightblue": "\\bbox[1pt,border-bottom: 2px solid #96ccff]",
                                "\\usolidlightestblue": "\\bbox[1pt,border-bottom: 2px solid #cdecff]",
                                "\\usolidwashedblue": "\\bbox[1pt,border-bottom: 2px solid #f6fffe]",
                                "\\usolidwashedgreen": "\\bbox[1pt,border-bottom: 2px solid #e8fdf5]",
                                "\\usolidwashedyellow": "\\bbox[1pt,border-bottom: 2px solid #fffceb]",
                                "\\usolidwashedred": "\\bbox[1pt,border-bottom: 2px solid #ffdfdf]",
                                "\\usolidgrey": "\\bbox[1pt,border-bottom: 2px solid #d3d3d3]",
                                "\\usolidgray": "\\bbox[1pt,border-bottom: 2px solid #d3d3d3]",
                                "\\usolid": "\\bbox[1pt,border-bottom: 2px solid #d3d3d3]",

                                "\\udoubledarkred": "\\bbox[1pt,border-bottom: 3px double #e7040f]",
                                "\\udoublered": "\\bbox[1pt,border-bottom: 3px double #ff4136]",
                                "\\udoublelightred": "\\bbox[1pt,border-bottom: 3px double #ff725c]",
                                "\\udoubleorange": "\\bbox[1pt,border-bottom: 3px double #ff6300]",
                                "\\udoublegold": "\\bbox[1pt,border-bottom: 3px double #ffb700]",
                                "\\udoubleyellow": "\\bbox[1pt,border-bottom: 3px double #ffde37]",
                                "\\udoublelightyellow": "\\bbox[1pt,border-bottom: 3px double #fbf1a9]",
                                "\\udoublepurple": "\\bbox[1pt,border-bottom: 3px double #5e2ca5]",
                                "\\udoublelightpurple": "\\bbox[1pt,border-bottom: 3px double #a463f2]",
                                "\\udoubledarkpink": "\\bbox[1pt,border-bottom: 3px double #d5008f]",
                                "\\udoublehotpink": "\\bbox[1pt,border-bottom: 3px double #ff41b4]",
                                "\\udoublepink": "\\bbox[1pt,border-bottom: 3px double #ff80cc]",
                                "\\udoublelightpink": "\\bbox[1pt,border-bottom: 3px double #ffa3d7]",
                                "\\udoubledarkgreen": "\\bbox[1pt,border-bottom: 3px double #137752]",
                                "\\udoublegreen": "\\bbox[1pt,border-bottom: 3px double #19a974]",
                                "\\udoublelightgreen": "\\bbox[1pt,border-bottom: 3px double #9eebcf]",
                                "\\udoublenavy": "\\bbox[1pt,border-bottom: 3px double #001b44]",
                                "\\udoubledarkblue": "\\bbox[1pt,border-bottom: 3px double #00449e]",
                                "\\udoubleblue": "\\bbox[1pt,border-bottom: 3px double #357edd]",
                                "\\udoublelightblue": "\\bbox[1pt,border-bottom: 3px double #96ccff]",
                                "\\udoublelightestblue": "\\bbox[1pt,border-bottom: 3px double #cdecff]",
                                "\\udoublewashedblue": "\\bbox[1pt,border-bottom: 3px double #f6fffe]",
                                "\\udoublewashedgreen": "\\bbox[1pt,border-bottom: 3px double #e8fdf5]",
                                "\\udoublewashedyellow": "\\bbox[1pt,border-bottom: 3px double #fffceb]",
                                "\\udoublewashedred": "\\bbox[1pt,border-bottom: 3px double #ffdfdf]",
                                "\\udoublegrey": "\\bbox[1pt,border-bottom: 3px double #d3d3d3]",
                                "\\udoublegray": "\\bbox[1pt,border-bottom: 3px double #d3d3d3]",
                                "\\udouble": "\\bbox[1pt,border-bottom: 3px double #d3d3d3]",
                            },
                            colorIsTextColor: true,
                        },
                    },
                ],
            },
        },
    ],
};
